#!/usr/bin/env python3
"""Embed data/font5x7.bdf into src/font_data.sml as a string literal.

sml-plot's `render` is self-contained: it parses a bitmap font at module load
time rather than reading a file at runtime, so the BDF text is baked into the
library source.  Re-run this after changing the vendored font:

    python3 tools/embed_font.py

The output is byte-stable: one SML source line per BDF line, joined with the
SML string gap (`\\` ... `\\`) so the embedded value is exactly the file's
bytes (each line terminated by "\\n").  The bundled font uses no `"` or `\\`
characters, but we escape them anyway for safety.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BDF = os.path.join(ROOT, "data", "font5x7.bdf")
OUT = os.path.join(ROOT, "src", "font_data.sml")


def sml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    with open(BDF, "r", newline="") as f:
        text = f.read()
    # Normalise to '\n'-terminated lines (the parser also strips trailing \r).
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]

    header = (
        "(* font_data.sml -- GENERATED by tools/embed_font.py; do not edit by hand.\n"
        "\n"
        "   The bundled 5x7 BDF font (data/font5x7.bdf) baked in as a string so that\n"
        "   Plot.render is self-contained and parses the font at module load with no\n"
        "   file I/O. *)\n"
        "\n"
        "structure FontData =\n"
        "struct\n"
        "  val bdf =\n"
    )

    # One SML source line per BDF line, glued with the SML string gap so the
    # embedded value is exactly the file's bytes (each terminated by "\n").
    out_lines = []
    n = len(lines)
    for i, ln in enumerate(lines):
        esc = sml_escape(ln)
        opener = '"' if i == 0 else "\\"
        closer = '"' if i == n - 1 else "\\"
        out_lines.append("    " + opener + esc + "\\n" + closer)

    with open(OUT, "w") as f:
        f.write(header)
        f.write("\n".join(out_lines))
        f.write("\nend\n")
    print("wrote %s (%d lines embedded)" % (OUT, n))


if __name__ == "__main__":
    main()
